"""
logger.py — Append interaction records to logs/query_log.jsonl.

Each line is a self-contained JSON object (JSON Lines format).
Feedback (thumbs up/down) is written as a separate update pass using the
entry's unique ID.

Log schema per entry (v1.3.0):
{
    "id":                   str,   # uuid4 — used to locate entry for feedback update
    "timestamp":            str,   # ISO-8601 UTC
    "session_id":           str,   # browser session uuid (groups a conversation)
    "query":                str,
    "rewritten_query":      str,   # resolved follow-up query (same as query if no rewrite)
    "classified_vertical":  str,
    "query_classification": str,   # safety classification: in_scope / clinical_decision / out_of_domain
    "intent":               str,   # question / troubleshooting / follow_up / casual / out_of_scope
    "formal_query":         str,   # rewritten query used for retrieval (from understand_query)
    "query_variants":       list,  # alternative phrasings generated by the rewriter
    "retrieved_chunks": [{"text": str, "source": str, "vertical": str, "score": float, "source_weight": float}],
    "top_chunk_score":      float, # highest score across all retrieved chunks
    "response":             str,
    "confidence":           str,   # high / medium / low (from CernaResponse)
    "refusal_flag":         bool,  # True if query was refused
    "refusal_reason":       str,   # out_of_domain / clinical_decision / "" if not refused
    "latency_ms":           int,   # total wall-clock ms
    "latency_retrieve_ms":  int,   # retrieval + rerank time
    "latency_generate_ms":  int,   # LLM generation time
    "rerank_enabled":       bool,
    "hyde_enabled":         bool,
    "cache_hit":            bool,
    "prompt_version":       str,
    "model_name":           str,
    "feedback":             null | "up" | "down"
}
"""

import json
import os
import uuid
from datetime import datetime, timezone
from pathlib import Path

from config import LOG_DIR, LOG_FILE, PROMPT_VERSION, GROQ_MODEL, RERANK_ENABLED, HYDE_ENABLED


def _ensure_log_dir():
    Path(LOG_DIR).mkdir(parents=True, exist_ok=True)


def log_interaction(
    query: str,
    classified_vertical: str,
    retrieved_chunks,
    response: str,
    latency_ms: int = 0,
    session_id: str | None = None,
    rewritten_query: str | None = None,
    query_classification: str = "in_scope",
    confidence: str = "medium",
    refusal_flag: bool = False,
    refusal_reason: str = "",
    latency_retrieve_ms: int = 0,
    latency_generate_ms: int = 0,
    cache_hit: bool = False,
    intent: str = "question",
    formal_query: str = "",
    query_variants: list | None = None,
) -> str:
    """
    Append a new interaction record to the JSONL log file.
    Returns entry_id (str) — the UUID used for feedback updates.
    """
    _ensure_log_dir()

    chunks_serialised = [
        {
            "text":         chunk.text[:300],
            "source":       chunk.source,
            "vertical":     chunk.vertical,
            "score":        chunk.score,
            "source_weight": getattr(chunk, "source_weight", 0.5),
        }
        for chunk in retrieved_chunks
    ]

    top_chunk_score = max((c["score"] for c in chunks_serialised), default=0.0)

    from pii_guard import mask_pii

    entry_id = str(uuid.uuid4())
    entry = {
        "id":                   entry_id,
        "timestamp":            datetime.now(timezone.utc).isoformat(),
        "session_id":           session_id or "unknown",
        "query":                mask_pii(query),
        "rewritten_query":      mask_pii(rewritten_query or query),
        "intent":               intent,
        "formal_query":         mask_pii(formal_query or rewritten_query or query),
        "query_variants":       [mask_pii(v) for v in (query_variants or [])],
        "classified_vertical":  classified_vertical,
        "query_classification": query_classification,
        "retrieved_chunks":     chunks_serialised,
        "top_chunk_score":      round(top_chunk_score, 4),
        "response":             response,
        "confidence":           confidence,
        "refusal_flag":         refusal_flag,
        "refusal_reason":       refusal_reason,
        "latency_ms":           latency_ms,
        "latency_retrieve_ms":  latency_retrieve_ms,
        "latency_generate_ms":  latency_generate_ms,
        "rerank_enabled":       RERANK_ENABLED,
        "hyde_enabled":         HYDE_ENABLED,
        "cache_hit":            cache_hit,
        "prompt_version":       PROMPT_VERSION,
        "model_name":           GROQ_MODEL,
        "feedback":             None,
    }

    try:
        with open(LOG_FILE, "a", encoding="utf-8") as f:
            f.write(json.dumps(entry, ensure_ascii=False) + "\n")
    except OSError as exc:
        print(f"[Logger] WARNING: could not write log entry: {exc}")

    return entry_id


def update_feedback(entry_id: str, feedback: str) -> bool:
    """
    Find the log entry with `entry_id` and update its feedback field in-place.
    Rewrites the entire file (JSONL files are small enough for this).
    Returns True if the entry was found and updated.
    """
    if not os.path.isfile(LOG_FILE):
        return False

    if feedback not in ("up", "down"):
        print(f"[Logger] Invalid feedback value: {feedback!r}. Use 'up' or 'down'.")
        return False

    try:
        with open(LOG_FILE, "r", encoding="utf-8") as f:
            lines = f.readlines()

        updated = False
        new_lines = []
        for line in lines:
            line = line.strip()
            if not line:
                continue
            try:
                entry = json.loads(line)
            except json.JSONDecodeError:
                new_lines.append(line)
                continue

            if entry.get("id") == entry_id:
                entry["feedback"] = feedback
                updated = True
            new_lines.append(json.dumps(entry, ensure_ascii=False))

        if updated:
            with open(LOG_FILE, "w", encoding="utf-8") as f:
                f.write("\n".join(new_lines) + "\n")

        return updated

    except OSError as exc:
        print(f"[Logger] WARNING: could not update feedback: {exc}")
        return False


def get_recent_logs(n: int = 10) -> list[dict]:
    """Return the last `n` log entries. Useful for debugging."""
    if not os.path.isfile(LOG_FILE):
        return []

    try:
        with open(LOG_FILE, "r", encoding="utf-8") as f:
            lines = [ln.strip() for ln in f if ln.strip()]
        entries = []
        for line in lines[-n:]:
            try:
                entries.append(json.loads(line))
            except json.JSONDecodeError:
                pass
        return entries
    except OSError:
        return []


def _test():
    from types import SimpleNamespace

    fake_chunk = SimpleNamespace(
        text="Prior authorization is a process by which payers require approval...",
        source="rcm-prior-auth-overview.txt",
        vertical="revenue_cycle",
        score=0.8912,
        source_weight=1.0,
    )

    print("[Test] Logging a fake interaction...")
    entry_id = log_interaction(
        query="What is prior authorization in Cerner Revenue Cycle?",
        classified_vertical="REVENUE_CYCLE",
        retrieved_chunks=[fake_chunk],
        response="Prior authorization in Cerner... [Source: rcm-prior-auth-overview.txt]",
        latency_ms=1234,
        session_id="test-session-abc123",
        rewritten_query="What is prior authorization in Cerner Revenue Cycle?",
        query_classification="in_scope",
        confidence="high",
        latency_retrieve_ms=210,
        latency_generate_ms=980,
        cache_hit=False,
    )
    print(f"  Entry ID: {entry_id}")

    print("[Test] Updating feedback to 'up'...")
    ok = update_feedback(entry_id, "up")
    print(f"  Updated: {ok}")

    logs = get_recent_logs(1)
    if logs:
        print(json.dumps(logs[-1], indent=2))

    print(f"\nLog file: {LOG_FILE}")


if __name__ == "__main__":
    _test()
