"""
tests/vague_queries.py — 40 realistic vague queries for benchmarking Cerna's
natural-language handling. 8 queries per Cerner module.

Mix of: one-word fragments, typos, symptom-not-feature ("list is empty"),
casual phrasing ("how do I chart vitals lol"), ambiguous ("the order thing"),
cross-module, and troubleshooting patterns.

These are the ground truth. Every pipeline change must improve pass rate on this
set without regressing formal queries from eval/golden_set.jsonl.

Pass criteria per query:
  - top semantic_score after retrieval > 0.40
  - at least one retrieved chunk's vertical matches expected_module (case-insensitive)
"""

VAGUE_QUERIES = [

    # ── CLINICAL (8) ──────────────────────────────────────────────────────────
    {
        "id": "cli_01",
        "query": "why won't my meds show up",
        "module": "CLINICAL",
        "expected_module": "clinical",
        "keywords": ["eMAR", "medication", "administration"],
        "description": "Medications not appearing in eMAR administration list",
    },
    {
        "id": "cli_02",
        "query": "nurse can't scan the barcode",
        "module": "CLINICAL",
        "expected_module": "clinical",
        "keywords": ["BCMA", "barcode", "scan"],
        "description": "BCMA barcode scanning failure during medication administration",
    },
    {
        "id": "cli_03",
        "query": "emar is broken",
        "module": "CLINICAL",
        "expected_module": "clinical",
        "keywords": ["eMAR", "medication"],
        "description": "eMAR not functioning — general troubleshooting",
    },
    {
        "id": "cli_04",
        "query": "how do nurses give meds",
        "module": "CLINICAL",
        "expected_module": "clinical",
        "keywords": ["eMAR", "medication administration", "BCMA"],
        "description": "Medication administration workflow for nurses",
    },
    {
        "id": "cli_05",
        "query": "wristband scan failed",
        "module": "CLINICAL",
        "expected_module": "clinical",
        "keywords": ["BCMA", "patient identification", "wristband"],
        "description": "Patient wristband barcode scanning failure in BCMA",
    },
    {
        "id": "cli_06",
        "query": "pharmacy isn't getting the order",
        "module": "CLINICAL",
        "expected_module": "clinical",
        "keywords": ["PharmNet", "pharmacy", "order"],
        "description": "Pharmacy not receiving medication orders from CPOE",
    },
    {
        "id": "cli_07",
        "query": "medication not on the admin list",
        "module": "CLINICAL",
        "expected_module": "clinical",
        "keywords": ["eMAR", "medication", "administration record"],
        "description": "Drug not appearing on eMAR administration record",
    },
    {
        "id": "cli_08",
        "query": "how do i chart vitals lol",
        "module": "CLINICAL",
        "expected_module": "clinical",
        "keywords": ["documentation", "vitals", "nursing"],
        "description": "Documenting vital signs in Cerner clinical workflow",
    },

    # ── POWERCHART (8) ────────────────────────────────────────────────────────
    {
        "id": "pc_01",
        "query": "patient list is empty",
        "module": "POWERCHART",
        "expected_module": "powerchart",
        "keywords": ["patient list", "PowerChart"],
        "description": "PowerChart patient list showing no patients",
    },
    {
        "id": "pc_02",
        "query": "can't find the patient",
        "module": "POWERCHART",
        "expected_module": "powerchart",
        "keywords": ["patient search", "PowerChart"],
        "description": "Patient search not returning results in PowerChart",
    },
    {
        "id": "pc_03",
        "query": "where do doctors write notes",
        "module": "POWERCHART",
        "expected_module": "powerchart",
        "keywords": ["PowerNote", "clinical documentation"],
        "description": "Clinical note documentation workflow in PowerChart",
    },
    {
        "id": "pc_04",
        "query": "how do i put in an order",
        "module": "POWERCHART",
        "expected_module": "powerchart",
        "keywords": ["CPOE", "order entry"],
        "description": "CPOE medication/lab order entry in PowerChart",
    },
    {
        "id": "pc_05",
        "query": "the order thing",
        "module": "POWERCHART",
        "expected_module": "powerchart",
        "keywords": ["CPOE", "order"],
        "description": "CPOE order management — extremely vague",
    },
    {
        "id": "pc_06",
        "query": "powerchat",
        "module": "POWERCHART",
        "expected_module": "powerchart",
        "keywords": ["PowerChart"],
        "description": "PowerChart overview — misspelling",
    },
    {
        "id": "pc_07",
        "query": "lab results not showing",
        "module": "POWERCHART",
        "expected_module": "powerchart",
        "keywords": ["results", "PowerChart"],
        "description": "Lab results not displaying in PowerChart results viewer",
    },
    {
        "id": "pc_08",
        "query": "inbox is full of alerts, how do i manage them",
        "module": "POWERCHART",
        "expected_module": "powerchart",
        "keywords": ["InBox", "alerts", "PowerChart"],
        "description": "Managing clinical alerts in PowerChart InBox",
    },

    # ── REVENUE_CYCLE (8) ─────────────────────────────────────────────────────
    {
        "id": "rcm_01",
        "query": "billing broken",
        "module": "REVENUE_CYCLE",
        "expected_module": "revenue_cycle",
        "keywords": ["revenue cycle", "billing", "charge"],
        "description": "General billing/RCM issue",
    },
    {
        "id": "rcm_02",
        "query": "why did the charge not go through",
        "module": "REVENUE_CYCLE",
        "expected_module": "revenue_cycle",
        "keywords": ["charge capture", "charge"],
        "description": "Charge capture failure troubleshooting",
    },
    {
        "id": "rcm_03",
        "query": "claim got denied",
        "module": "REVENUE_CYCLE",
        "expected_module": "revenue_cycle",
        "keywords": ["denial", "claim"],
        "description": "Claim denial management in RCM",
    },
    {
        "id": "rcm_04",
        "query": "how does coding work",
        "module": "REVENUE_CYCLE",
        "expected_module": "revenue_cycle",
        "keywords": ["HIM", "coding", "CDI"],
        "description": "HIM coding and CDI workflow in Revenue Cycle",
    },
    {
        "id": "rcm_05",
        "query": "patient owes money but system doesn't show it",
        "module": "REVENUE_CYCLE",
        "expected_module": "revenue_cycle",
        "keywords": ["patient accounting", "balance"],
        "description": "Patient balance not showing in patient accounting",
    },
    {
        "id": "rcm_06",
        "query": "revelate",
        "module": "REVENUE_CYCLE",
        "expected_module": "revenue_cycle",
        "keywords": ["RevElate"],
        "description": "RevElate platform — single word query",
    },
    {
        "id": "rcm_07",
        "query": "how do i fix a claim",
        "module": "REVENUE_CYCLE",
        "expected_module": "revenue_cycle",
        "keywords": ["claim", "revenue cycle"],
        "description": "Claim correction/resubmission workflow",
    },
    {
        "id": "rcm_08",
        "query": "why is the charge not coming through after the nurse documents",
        "module": "REVENUE_CYCLE",
        "expected_module": "revenue_cycle",
        "keywords": ["charge capture", "nursing", "revenue cycle"],
        "description": "Cross-module: charge not generated after nursing documentation",
    },

    # ── FHIR (8) ──────────────────────────────────────────────────────────────
    {
        "id": "fhir_01",
        "query": "how to connect my app to cerner",
        "module": "FHIR",
        "expected_module": "fhir",
        "keywords": ["FHIR", "API", "SMART"],
        "description": "Connecting an application to Cerner via FHIR API",
    },
    {
        "id": "fhir_02",
        "query": "api not working",
        "module": "FHIR",
        "expected_module": "fhir",
        "keywords": ["FHIR", "API"],
        "description": "FHIR API troubleshooting",
    },
    {
        "id": "fhir_03",
        "query": "how do i pull patient data",
        "module": "FHIR",
        "expected_module": "fhir",
        "keywords": ["FHIR", "patient", "API"],
        "description": "Retrieving patient data via FHIR API",
    },
    {
        "id": "fhir_04",
        "query": "SMART thing",
        "module": "FHIR",
        "expected_module": "fhir",
        "keywords": ["SMART on FHIR", "app launch"],
        "description": "SMART on FHIR app launch — vague reference",
    },
    {
        "id": "fhir_05",
        "query": "oauth setup",
        "module": "FHIR",
        "expected_module": "fhir",
        "keywords": ["OAuth", "authorization", "FHIR"],
        "description": "OAuth 2.0 setup for Cerner FHIR integration",
    },
    {
        "id": "fhir_06",
        "query": "fhir error 401",
        "module": "FHIR",
        "expected_module": "fhir",
        "keywords": ["FHIR", "401", "authorization"],
        "description": "FHIR API 401 authorization error troubleshooting",
    },
    {
        "id": "fhir_07",
        "query": "how to get lab results from the API",
        "module": "FHIR",
        "expected_module": "fhir",
        "keywords": ["FHIR", "Observation", "laboratory"],
        "description": "Retrieving lab results via FHIR Observation resource",
    },
    {
        "id": "fhir_08",
        "query": "hl7 message not arriving",
        "module": "FHIR",
        "expected_module": "fhir",
        "keywords": ["HL7", "message", "interface"],
        "description": "HL7 v2 interface message delivery troubleshooting",
    },

    # ── MILLENNIUM (8) ────────────────────────────────────────────────────────
    {
        "id": "mil_01",
        "query": "how does cerner backend work",
        "module": "MILLENNIUM",
        "expected_module": "millennium",
        "keywords": ["Millennium", "domain", "architecture"],
        "description": "Cerner Millennium platform architecture overview",
    },
    {
        "id": "mil_02",
        "query": "ccl script not running",
        "module": "MILLENNIUM",
        "expected_module": "millennium",
        "keywords": ["CCL", "script", "Millennium"],
        "description": "CCL scripting troubleshooting in Millennium",
    },
    {
        "id": "mil_03",
        "query": "millenium domain",
        "module": "MILLENNIUM",
        "expected_module": "millennium",
        "keywords": ["Millennium", "domain"],
        "description": "Millennium domain overview/config — misspelling",
    },
    {
        "id": "mil_04",
        "query": "mpage not loading",
        "module": "MILLENNIUM",
        "expected_module": "millennium",
        "keywords": ["MPages", "Millennium"],
        "description": "MPages loading failure troubleshooting",
    },
    {
        "id": "mil_05",
        "query": "how do i customize the homepage",
        "module": "MILLENNIUM",
        "expected_module": "millennium",
        "keywords": ["MPages", "customization"],
        "description": "Millennium/PowerChart homepage customization via MPages",
    },
    {
        "id": "mil_06",
        "query": "upgrade broke everything",
        "module": "MILLENNIUM",
        "expected_module": "millennium",
        "keywords": ["upgrade", "Millennium"],
        "description": "Post-upgrade issues in Cerner Millennium",
    },
    {
        "id": "mil_07",
        "query": "discern report wrong",
        "module": "MILLENNIUM",
        "expected_module": "millennium",
        "keywords": ["Discern", "Analytics", "reporting"],
        "description": "Discern Analytics report returning incorrect results",
    },
    {
        "id": "mil_08",
        "query": "what is cerner",
        "module": "MILLENNIUM",
        "expected_module": "millennium",
        "keywords": ["Cerner", "Oracle Health", "Millennium"],
        "description": "General overview of Cerner/Oracle Health platform",
    },
    # ── Additional FHIR (5) ───────────────────────────────────────────────────
    {
        "id": "fhir_09",
        "query": "patient not found in the api",
        "module": "FHIR",
        "expected_module": "fhir",
        "keywords": ["FHIR", "patient", "404", "resource"],
        "description": "FHIR API 404 patient resource not found troubleshooting",
    },
    {
        "id": "fhir_10",
        "query": "how to register a cerner app",
        "module": "FHIR",
        "expected_module": "fhir",
        "keywords": ["FHIR", "developer", "app registration", "SMART"],
        "description": "Registering an app with Cerner FHIR developer portal",
    },
    {
        "id": "fhir_11",
        "query": "getting a 403 on the endpoint",
        "module": "FHIR",
        "expected_module": "fhir",
        "keywords": ["FHIR", "403", "authorization", "OAuth", "scope"],
        "description": "FHIR API 403 forbidden authorization scope error",
    },
    {
        "id": "fhir_12",
        "query": "careaware not syncing",
        "module": "FHIR",
        "expected_module": "fhir",
        "keywords": ["CareAware", "integration", "sync"],
        "description": "CareAware Connect integration synchronization failure",
    },
    {
        "id": "fhir_13",
        "query": "how do i get a patient's labs via api",
        "module": "FHIR",
        "expected_module": "fhir",
        "keywords": ["FHIR", "Observation", "laboratory", "API"],
        "description": "Retrieving lab results via FHIR Observation resource",
    },

    # ── Cross-module (5) ──────────────────────────────────────────────────────
    {
        "id": "cross_01",
        "query": "nurse gave a med but charge didn't appear",
        "module": "REVENUE_CYCLE",
        "expected_module": "revenue_cycle",
        "keywords": ["charge capture", "eMAR", "nursing documentation", "revenue cycle"],
        "description": "Cross-module: nursing eMAR administration not generating RCM charge",
    },
    {
        "id": "cross_02",
        "query": "order was placed but pharmacy never got it",
        "module": "CLINICAL",
        "expected_module": "clinical",
        "keywords": ["PharmNet", "CPOE", "pharmacy", "order routing"],
        "description": "Cross-module: CPOE order not routing to PharmNet pharmacy",
    },
    {
        "id": "cross_03",
        "query": "my third party app shows wrong patient data",
        "module": "FHIR",
        "expected_module": "fhir",
        "keywords": ["FHIR", "patient data", "third party", "integration"],
        "description": "Cross-module: FHIR API returning incorrect patient data to external app",
    },
    {
        "id": "cross_04",
        "query": "patient got discharged but still showing as admitted",
        "module": "POWERCHART",
        "expected_module": "powerchart",
        "keywords": ["PowerChart", "discharge", "ADT", "patient status"],
        "description": "Cross-module: discharge status not updating in PowerChart/Millennium ADT",
    },
    {
        "id": "cross_05",
        "query": "coder can't find the diagnosis in the chart",
        "module": "REVENUE_CYCLE",
        "expected_module": "revenue_cycle",
        "keywords": ["CDI", "HIM coding", "diagnosis", "PowerChart", "revenue cycle"],
        "description": "Cross-module: HIM coder cannot locate diagnosis documentation in clinical chart",
    },
]

# ── Formal baseline queries (regression guard) ────────────────────────────────
# These already worked before. Must continue to pass after any change.
FORMAL_QUERIES = [
    {"id": "f_01", "query": "How do I configure eMAR integration with Millennium MOM?",
     "module": "CLINICAL", "expected_module": "clinical"},
    {"id": "f_02", "query": "What is the FHIR R4 Patient resource search parameters?",
     "module": "FHIR", "expected_module": "fhir"},
    {"id": "f_03", "query": "How does charge capture work in Revenue Cycle?",
     "module": "REVENUE_CYCLE", "expected_module": "revenue_cycle"},
    {"id": "f_04", "query": "Explain the Millennium domain architecture",
     "module": "MILLENNIUM", "expected_module": "millennium"},
    {"id": "f_05", "query": "How do I configure PowerChart patient lists?",
     "module": "POWERCHART", "expected_module": "powerchart"},
]
