"""
validate_source_urls.py — HEAD-check every public source URL in data/ headers.

Reads the URL map produced by source_urls._url_map(), pings each URL with a
HEAD (falls back to GET if HEAD is rejected), and writes any URL that returns
404/410 or fails to resolve into data/_dead_urls.txt — one URL per line.

source_urls.py loads that denylist on first call and excludes those URLs from
get_url(), so the UI never surfaces a broken link.

Usage:
    python scripts/validate_source_urls.py
    python scripts/validate_source_urls.py --timeout 5 --workers 16
"""

from __future__ import annotations

import argparse
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

import requests

# Add repo root to sys.path so we can import source_urls.py when run as a script
_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from source_urls import _url_map  # noqa: E402

_DEAD_FILE = _REPO_ROOT / "data" / "_dead_urls.txt"
_DEAD_STATUSES = {404, 410}  # Treat these as definitely-dead
_OK_RANGE = range(200, 400)  # 2xx + 3xx (redirects to a working page) = alive

_HEADERS = {
    # Some servers 403 on bot UAs; mimic a real browser
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/124.0 Safari/537.36"
    ),
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
}


def check_one(url: str, timeout: float) -> tuple[str, int | str]:
    """Return (url, status). status is HTTP code int, or error string."""
    try:
        # Try HEAD first (cheap), fall back to GET if server rejects it
        r = requests.head(url, headers=_HEADERS, timeout=timeout, allow_redirects=True)
        if r.status_code in (405, 501) or r.status_code == 403:
            r = requests.get(url, headers=_HEADERS, timeout=timeout, allow_redirects=True, stream=True)
            r.close()
        return url, r.status_code
    except requests.exceptions.Timeout:
        return url, "timeout"
    except requests.exceptions.ConnectionError:
        return url, "conn_error"
    except requests.exceptions.RequestException as exc:
        return url, f"err:{type(exc).__name__}"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--timeout", type=float, default=6.0, help="Per-URL timeout seconds")
    parser.add_argument("--workers", type=int, default=12, help="Concurrent HEAD requests")
    args = parser.parse_args()

    url_map = _url_map()
    urls = sorted({v[1] for v in url_map.values() if v[1]})
    if not urls:
        print("[validate] No URLs found in data/ headers.")
        return 0

    print(f"[validate] checking {len(urls)} unique URLs (timeout={args.timeout}s, workers={args.workers})")

    dead: list[tuple[str, int | str]] = []
    unreachable: list[tuple[str, str]] = []  # Network errors — not necessarily dead
    t0 = time.time()

    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        futures = {pool.submit(check_one, u, args.timeout): u for u in urls}
        for i, fut in enumerate(as_completed(futures), 1):
            url, status = fut.result()
            if isinstance(status, int):
                if status in _DEAD_STATUSES:
                    dead.append((url, status))
                    print(f"  [{i}/{len(urls)}] DEAD {status}  {url}")
                elif status not in _OK_RANGE:
                    # Unusual codes (e.g. 5xx) — flag but don't denylist
                    print(f"  [{i}/{len(urls)}] ?{status}  {url}")
            else:
                unreachable.append((url, status))

    elapsed = time.time() - t0

    # Only write the denylist for definitively dead URLs (404/410).
    # Unreachable URLs (timeouts / connection errors) often come back later
    # or indicate corporate proxy blocks — denylisting them would risk
    # removing valid sources.
    _DEAD_FILE.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# Auto-generated by scripts/validate_source_urls.py\n"
        "# Each URL on this list returns 404/410 and is excluded from rendered references.\n"
        "# Re-run periodically to refresh: python scripts/validate_source_urls.py\n"
    )
    body = "\n".join(url for url, _ in sorted(dead))
    _DEAD_FILE.write_text(header + body + ("\n" if body else ""), encoding="utf-8")

    print()
    print(f"[validate] Done in {elapsed:.1f}s")
    print(f"[validate] Dead (404/410): {len(dead)}")
    print(f"[validate] Unreachable (network errors, not denylisted): {len(unreachable)}")
    print(f"[validate] Denylist written -> {_DEAD_FILE.relative_to(_REPO_ROOT)}")
    if unreachable:
        print("[validate] Unreachable URLs (not denylisted — likely transient or proxy-blocked):")
        for u, err in unreachable[:10]:
            print(f"    {err:15s}  {u}")
        if len(unreachable) > 10:
            print(f"    ... and {len(unreachable) - 10} more")
    return 0


if __name__ == "__main__":
    sys.exit(main())
